### model
model_name_or_path: Qwen/Qwen2.5-7B
trust_remote_code: true

### method
stage: sft
do_train: true
finetuning_type: lora
lora_rank: 8
lora_alpha: 16
lora_dropout: 0.2
lora_target: q_proj,k_proj,v_proj,o_proj,up_proj,down_proj,gate_proj

### dataset
dataset: letter_concat_ascii_multiply_composable_cot_train
template: empty
cutoff_len: 768
max_samples: 600
overwrite_cache: true
preprocessing_num_workers: 16
dataloader_num_workers: 4

### output
output_dir: ../model_ckpt/letter_concat_ascii_multiply_composable_cot
logging_steps: 100
save_strategy: epoch
plot_loss: true
overwrite_output_dir: true
save_only_model: false
load_best_model_at_end: true
bf16: true
save_total_limit: 1
metric_for_best_model: eval_loss

### train
per_device_train_batch_size: 4
gradient_accumulation_steps: 1
learning_rate: 1.0e-4
num_train_epochs: 5.0
lr_scheduler_type: linear
bf16: true
ddp_timeout: 180000000
resume_from_checkpoint: null

## eval
eval_dataset: letter_concat_ascii_multiply_composable_cot_val
per_device_eval_batch_size: 2
eval_strategy: epoch
report_to: none
